# Generated by Django 5.2.7 on 2025-10-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_field',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_percentage',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
